### PR TITLE
Revert "Switch to PyQt5 instead of PyQt4 when using conda"

### PR DESCRIPTION
**Pull request by tkelman**
Reverts JuliaPy/PyPlot.jl#243 since it looks like conda changed their mind and are back to qt4

### CODE REVIEW

**Comment by stevengj** [comment]
We should really check for both so that we don't have to patch for future changes.

**Comment by tkelman** [comment]
yes, good idea. what's the best way to go about that? just a try catch?

**Comment by stevengj** [comment]
Yeah, probably just a `try-catch`

**Comment by tbreloff** [comment]
FYI this broke PyPlot for me, and doing `Pkg.pin("PyPlot", v"2.2.3")` fixed it.  I was getting errors:

```
ERROR: InitError: PyError (:PyImport_ImportModule) <type 'exceptions.ImportError'>
ImportError('No module named PyQt4',)

 in pyerr_check at /home/tom/.julia/v0.5/PyCall/src/exception.jl:56 [inlined]
 in pyerr_check at /home/tom/.julia/v0.5/PyCall/src/exception.jl:61 [inlined]
 in macro expansion at /home/tom/.julia/v0.5/PyCall/src/exception.jl:81 [inlined]
 in pyimport(::String) at /home/tom/.julia/v0.5/PyCall/src/PyCall.jl:387
 in pyimport_conda(::String, ::String, ::String) at /home/tom/.julia/v0.5/PyCall/src/PyCall.jl:480
 in find_backend(::PyCall.PyObject) at /home/tom/.julia/v0.5/PyPlot/src/PyPlot.jl:137
 in __init__() at /home/tom/.julia/v0.5/PyPlot/src/PyPlot.jl:230
 in _include_from_serialized(::String) at ./loading.jl:150
 in _require_from_serialized(::Int64, ::Symbol, ::String, ::Bool) at ./loading.jl:187
 in require(::Symbol) at ./loading.jl:394
 in _initialize_backend(::Plots.PyPlotBackend) at /home/tom/.julia/v0.5/Plots/src/backends/pyplot.jl:63
 in backend() at /home/tom/.julia/v0.5/Plots/src/backends.jl:151
 in #pyplot#137(::Array{Any,1}, ::Function) at /home/tom/.julia/v0.5/Plots/src/backends.jl:20
 in pyplot() at /home/tom/.julia/v0.5/Plots/src/backends.jl:20
during initialization of module PyPlot
```

**Comment by tkelman** [comment]
Where's your pyqt from? when was it updated?

**Pull request merged**
